# coding: utf-8

"""
    Business Management API

    API to manage customers in a business system.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Business Management API",
    description="API to manage customers in a business system.",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
